repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (update periodically by running 'pre-commit autoupdate')
  rev: v0.6.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
-   repo: local
    hooks:
    - id: check-notebook-outputs
      name: Check that notebooks have no output cells.
      description: Verifies that documentation notebooks contain no output cells.
      language: python
      pass_filenames: false
      entry: python ./docs/clean_notebooks.py --dryrun ./docs