name: Other Issues and Tasks
description: An issue pertaining to Dymos-related items like documentation, the website, github actions, etc.
assignees:
  - robfalck
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Please describe the task to be performed.
    validations:
      required: true
