# Publish release to PyPi

name: Dymos Release

on:
  # Trigger on release, to publish release packages to PyPI
  release:
    types: [published]

  # Trigger via workflow_dispatch event (manual trigger FOR TESTING ONLY)
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: deps
        run: python -m pip install -U hatch

      - name: build
        run: hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # this is just for testing, remove for flight:
        with:
          repository-url: https://test.pypi.org/legacy/
