name: Publish Image

on:
  release:
    types: [published]

  # Run the workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Will use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Get tags
        run: |
          git fetch --unshallow --tags
          git describe --tags > tag.txt
          echo "TAG=$(cat tag.txt)" >> $GITHUB_ENV

      # Login against the registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.TAG }}

      # Build and push image with Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.image_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
